// countriesData.ts

const countries = [
    { label: 'E-Mail-Abo Patient', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/reiseinformationen/rhreg.html' },
    { label: 'Afghanistan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/afghanistan/reisehinweise-afghanistan.html' },
    { label: 'Ägypten', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/aegypten/reisehinweise-aegypten.html' },
    { label: 'Albanien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/albanien/reisehinweise-albanien.html' },
    { label: 'Algerien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/algerien/reisehinweise-algerien.html' },
    { label: 'Andorra', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/andorra/reisehinweise-andorra.html' },
    { label: 'Angola', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/angola/reisehinweise-angola.html' },
    { label: 'Antigua und Barbuda', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/antigua_und_barbuda/reisehinweise-antigua-und-barbuda.html' },
    { label: 'Äquatorialguinea', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/aequatorialguinea/reisehinweise-aequatorialguinea.html' },
    { label: 'Argentinien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/argentinien/reisehinweise-argentinien.html' },
    { label: 'Armenien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/armenien/reisehinweise-armenien.html' },
    { label: 'Aserbaidschan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/aserbaidschan/reisehinweise-aserbaidschan.html' },
    { label: 'Äthiopien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/aethiopien/reisehinweise-aethiopien.html' },
    { label: 'Australien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/australien/reisehinweise-australien.html' },
    { label: 'Bahamas', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/bahamas/reisehinweise-bahamas.html' },
    { label: 'Bahrain', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/bahrain/reisehinweise-bahrain.html' },
    { label: 'Bangladesch', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/bangladesch/reisehinweise-bangladesch.html' },
    { label: 'Barbados', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/barbados/reisehinweise-barbados.html' },
    { label: 'Belarus', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/belarus/reisehinweise-belarus.html' },
    { label: 'Belgien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/belgien/reisehinweise-belgien.html' },
    { label: 'Belize', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/belize/reisehinweise-belize.html' },
    { label: 'Benin', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/benin/reisehinweise-benin.html' },
    { label: 'Besetztes Palästinensisches Gebiet', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/palaestinensischebehoerde/reisehinweise-palaestinensische-behoerde.html' },
    { label: 'Bhutan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/bhutan/reisehinweise-bhutan.html' },
    { label: 'Bolivien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/bolivien/reisehinweise-bolivien.html' },
    { label: 'Bosnien und Herzegowina', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/bosnien_und_herzegowina/reisehinweise-bosnien-und-herzegowina.html' },
    { label: 'Botsuana', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/botsuana/reisehinweise-botsuana.html' },
    { label: 'Brasilien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/brasilien/reisehinweise-brasilien.html' },
    { label: 'Brunei Darussalam', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/brunei_darussalam/reisehinweise-brunei-darussalam.html' },
    { label: 'Bulgarien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/bulgarien/reisehinweise-bulgarien.html' },
    { label: 'Burkina Faso', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/burkina_faso/reisehinweise-burkina-faso.html' },
    { label: 'Burundi', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/burundi/reisehinweise-burundi.html' },
    { label: 'Cabo Verde', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kap_verde/reisehinweise-kap-verde.html' },
    { label: 'China', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/china/reisehinweise-china.html' },
    { label: 'Chile', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/chile/reisehinweise-chile.html' },
    { label: 'Cookinseln', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/cookinseln/reisehinweise-cookinseln.html' },
    { label: 'Costa Rica', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/costa_rica/reisehinweise-costa-rica.html' },
    { label: 'Dänemark', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/daenemark/reisehinweise-daenemark.html' },
    { label: 'Deutschland', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/deutschland/reisehinweise-deutschland.html' },
    { label: 'Dominica', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/dominica/reisehinweise-dominica.html' },
    { label: 'Dominikanische Republik', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/dominikanische_republik/reisehinweise-dominikanische-republik.html' },
    { label: 'Dschibuti', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/dschibuti/reisehinweise-dschibuti.html' },
    { label: 'Ecuador', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/ecuador/reisehinweise-ecuador.html' },
    { label: 'El Salvador', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/el_salvador/reisehinweise-el-salvador.html' },
    { label: 'Elfenbeinküste', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/cote_d_ivoire/reisehinweise-cote-d-ivoire.html' },
    { label: 'Eritrea', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/eritrea/reisehinweise-eritrea.html' },
    { label: 'Estland', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/estland/reisehinweise-estland.html' },
    { label: 'Eswatini', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/eswatini/reisehinweise-eswatini.html' },
    { label: 'Fidschi', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/republik_fidschi/reisehinweise-fidschi.html' },
    { label: 'Finnland', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/finnland/reisehinweise-finnland.html' },
    { label: 'Frankreich', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/frankreich/reisehinweise-frankreich.html' },
    { label: 'Gabun', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/gabun/reisehinweise-gabun.html' },
    { label: 'Gambia', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/gambia/reisehinweise-gambia.html' },
    { label: 'Georgien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/georgien/reisehinweise-georgien.html' },
    { label: 'Ghana', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/ghana/reisehinweise-ghana.html' },
    { label: 'Grenada', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/grenada/reisehinweise-grenada.html' },
    { label: 'Griechenland', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/griechenland/reisehinweise-griechenland.html' },
    { label: 'Guatemala', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/guatemala/reisehinweise-guatemala.html' },
    { label: 'Guinea', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/guinea/reisehinweise-guinea.html' },
    { label: 'Guinea-Bissau', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/guinea-bissau/reisehinweise-guinea-bissau.html' },
    { label: 'Guyana', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/guyana/reisehinweise-guyana.html' },
    { label: 'Haiti', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/haiti/reisehinweise-haiti.html' },
    { label: 'Honduras', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/honduras/reisehinweise-honduras.html' },
    { label: 'Indien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/indien/reisehinweise-indien.html' },
    { label: 'Indonesien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/indonesien/reisehinweise-indonesien.html' },
    { label: 'Irak', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/irak/reisehinweise-irak.html' },
    { label: 'Iran', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/iran/reisehinweise-iran.html' },
    { label: 'Irland', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/irland/reisehinweise-irland.html' },
    { label: 'Island', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/island/reisehinweise-island.html' },
    { label: 'Israel', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/israel/reisehinweise-israel.html' },
    { label: 'Italien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/italien/reisehinweise-italien.html' },
    { label: 'Jamaika', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/jamaika/reisehinweise-jamaika.html' },
    { label: 'Japan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/japan/reisehinweise-japan.html' },
    { label: 'Jemen', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/jemen/reisehinweise-jemen.html' },
    { label: 'Jordanien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/jordanien/reisehinweise-jordanien.html' },
    { label: 'Kambodscha', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kambodscha/reisehinweise-kambodscha.html' },
    { label: 'Kamerun', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kamerun/reisehinweise-kamerun.html' },
    { label: 'Kanada', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kanada/reisehinweise-kanada.html' },
    { label: 'Kasachstan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kasachstan/reisehinweise-kasachstan.html' },
    { label: 'Katar', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/katar/reisehinweise-katar.html' },
    { label: 'Kenia', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kenia/reisehinweise-kenia.html' },
    { label: 'Kirgisistan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kirgisistan/reisehinweise-kirgisistan.html' },
    { label: 'Kiribati', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kiribati/reisehinweise-kiribati.html' },
    { label: 'Kolumbien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kolumbien/reisehinweise-kolumbien.html' },
    { label: 'Komoren', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/komoren/reisehinweise-komoren.html' },
    { label: 'Kongo, Demokratische Republik (Kinshasa)', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/demokratische_republikkongo/reisehinweise-demokratische-republik-kongo.html' },
    { label: 'Kongo, Republik (Brazzaville)', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/republik_kongo/reisehinweise-republik-kongo.html' },
    { label: 'Korea, Demokratische Volksrepublik (Nord-)', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/demokratische_volksrepublikkorea/reisehinweise-demokratische-volksrepublik-korea.html' },
    { label: 'Korea, Republik (Süd-)', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/republik_korea/reisehinweise-republik-korea.html' },
    { label: 'Kosovo', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kosovo/reisehinweise-kosovo.html' },
    { label: 'Kroatien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kroatien/reisehinweise-kroatien.html' },
    { label: 'Kuba', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kuba/reisehinweise-kuba.html' },
    { label: 'Kuwait', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/kuwait/reisehinweise-kuwait.html' },
    { label: 'Laos', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/laos/reisehinweise-laos.html' },
    { label: 'Lesotho', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/lesotho/reisehinweise-lesotho.html' },
    { label: 'Lettland', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/lettland/reisehinweise-lettland.html' },
    { label: 'Libanon', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/libanon/reisehinweise-libanon.html' },
    { label: 'Liberia', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/liberia/reisehinweise-liberia.html' },
    { label: 'Libyen', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/libyen/reisehinweise-libyen.html' },
    { label: 'Liechtenstein', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/liechtenstein/reisehinweise-liechtenstein.html' },
    { label: 'Litauen', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/litauen/reisehinweise-litauen.html' },
    { label: 'Luxemburg', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/luxemburg/reisehinweise-luxemburg.html' },
    { label: 'Macao', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/macao/reisehinweise-macao.html' },
    { label: 'Madagaskar', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/madagaskar/reisehinweise-madagaskar.html' },
    { label: 'Malawi', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/malawi/reisehinweise-malawi.html' },
    { label: 'Malaysia', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/malaysia/reisehinweise-malaysia.html' },
    { label: 'Malediven', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/malediven/reisehinweise-malediven.html' },
    { label: 'Mali', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/mali/reisehinweise-mali.html' },
    { label: 'Malta', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/malta/reisehinweise-malta.html' },
    { label: 'Marokko', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/marokko/reisehinweise-marokko.html' },
    { label: 'Marschallinseln', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/marschallinseln/reisehinweise-marschallinseln.html' },
    { label: 'Mauretanien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/mauretanien/reisehinweise-mauretanien.html' },
    { label: 'Mauritius', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/mauritius/reisehinweise-mauritius.html' },
    { label: 'Mexiko', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/mexiko/reisehinweise-mexiko.html' },
    { label: 'Mikronesien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/mikronesien/reisehinweise-mikronesien.html' },
    { label: 'Moldau', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/moldova/reisehinweise-moldova.html' },
    { label: 'Monaco', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/monaco/reisehinweise-monaco.html' },
    { label: 'Mongolei', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/mongolei/reisehinweise-mongolei.html' },
    { label: 'Montenegro', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/montenegro/reisehinweise-montenegro.html' },
    { label: 'Mosambik', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/mosambik/reisehinweise-mosambik.html' },
    { label: 'Myanmar', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/myanmar/reisehinweise-myanmar.html' },
    { label: 'Namibia', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/namibia/reisehinweise-namibia.html' },
    { label: 'Nauru', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/nauru/reisehinweise-nauru.html' },
    { label: 'Nepal', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/nepal/reisehinweise-nepal.html' },
    { label: 'Neuseeland', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/neuseeland/reisehinweise-neuseeland.html' },
    { label: 'Nicaragua', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/nicaragua/reisehinweise-nicaragua.html' },
    { label: 'Niederlande', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/niederlande/reisehinweise-niederlande.html' },
    { label: 'Niger', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/niger/reisehinweise-niger.html' },
    { label: 'Nigeria', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/nigeria/reisehinweise-nigeria.html' },
    { label: 'Nordmazedonien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/nordmazedonien/reisehinweise-nordmazedonien.html' },
    { label: 'Norwegen', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/norwegen/reisehinweise-norwegen.html' },
    { label: 'Oman', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/oman/reisehinweise-oman.html' },
    { label: 'Österreich', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/oesterreich/reisehinweise-oesterreich.html' },
    { label: 'Pakistan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/pakistan/reisehinweise-pakistan.html' },
    { label: 'Palau', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/palau/reisehinweise-palau.html' },
    { label: 'Panama', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/panama/reisehinweise-panama.html' },
    { label: 'Papua-Neuguinea', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/papua-neuguinea/reisehinweise-papua-neuguinea.html' },
    { label: 'Paraguay', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/paraguay/reisehinweise-paraguay.html' },
    { label: 'Peru', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/peru/reisehinweise-peru.html' },
    { label: 'Philippinen', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/philippinen/reisehinweise-philippinen.html' },
    { label: 'Polen', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/polen/reisehinweise-polen.html' },
    { label: 'Portugal', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/portugal/reisehinweise-portugal.html' },
    { label: 'Ruanda', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/ruanda/reisehinweise-ruanda.html' },
    { label: 'Rumänien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/rumaenien/reisehinweise-rumaenien.html' },
    { label: 'Russland', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/russland/reisehinweise-russland.html' },
    { label: 'Salomoninseln', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/salomoninseln/reisehinweise-salomoninseln.html' },
    { label: 'Sambia', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/sambia/reisehinweise-sambia.html' },
    { label: 'Samoa', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/samoa/reisehinweise-samoa.html' },
    { label: 'San Marino', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/san_marino/reisehinweise-san-marino.html' },
    { label: 'São Tomé und Príncipe', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/sao_tome_und_principe/reisehinweise-sao-tome-und-principe.html' },
    { label: 'Saudi-Arabien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/saudi_arabien/reisehinweise-saudi-arabien.html' },
    { label: 'Schweden', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/schweden/reisehinweise-schweden.html' },
    { label: 'Senegal', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/senegal/reisehinweise-senegal.html' },
    { label: 'Serbien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/serbien/reisehinweise-serbien.html' },
    { label: 'Seychellen', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/seychellen/reisehinweise-seychellen.html' },
    { label: 'Sierra Leone', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/sierra_leone/reisehinweise-sierra-leone.html' },
    { label: 'Simbabwe', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/simbabwe/reisehinweise-simbabwe.html' },
    { label: 'Singapur', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/singapur/reisehinweise-singapur.html' },
    { label: 'Slowakei', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/slowakei/reisehinweise-slowakei.html' },
    { label: 'Slowenien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/slowenien/reisehinweise-slowenien.html' },
    { label: 'Somalia', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/somalia/reisehinweise-somalia.html' },
    { label: 'Spanien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/spanien/reisehinweise-spanien.html' },
    { label: 'Sri Lanka', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/sri_lanka/reisehinweise-sri-lanka.html' },
    { label: 'St. Kitts und Nevis', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/st_kitts_und_nevis/reisehinweise-st-kitts-und-nevis.html' },
    { label: 'St. Lucia', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/st_lucia/reisehinweise-st-lucia.html' },
    { label: 'St. Vincent und die Grenadinen', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/st_vincent_und_diegrenadinen/reisehinweise-st-vincent-und-die-grenadinen.html' },
    { label: 'Südafrika', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/suedafrika/reisehinweise-suedafrika.html' },
    { label: 'Sudan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/sudan/reisehinweise-sudan.html' },
    { label: 'Südsudan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/suedsudan/reisehinweise-suedsudan.html' },
    { label: 'Suriname', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/suriname/reisehinweise-suriname.html' },
    { label: 'Syrien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/syrien/reisehinweise-syrien.html' },
    { label: 'Tadschikistan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/tadschikistan/reisehinweise-tadschikistan.html' },
    { label: 'Taiwan (Chinesisches Taipei)', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/taiwan_taipei_/reisehinweise-taiwan-taipei.html' },
    { label: 'Tansania', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/tansania/reisehinweise-tansania.html' },
    { label: 'Thailand', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/thailand/reisehinweise-thailand.html' },
    { label: 'Timor-Leste', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/timor-leste/reisehinweise-timor-leste.html' },
    { label: 'Togo', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/togo/reisehinweise-togo.html' },
    { label: 'Tonga', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/tonga/reisehinweise-tonga.html' },
    { label: 'Trinidad und Tobago', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/trinidad_und_tobago/reisehinweise-trinidad-und-tobago.html' },
    { label: 'Tschad', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/tschad/reisehinweise-tschad.html' },
    { label: 'Tschechien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/tschechische_republik/reisehinweise-tschechische-republik.html' },
    { label: 'Tunesien', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/tunesien/reisehinweise-tunesien.html' },
    { label: 'Türkei', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/tuerkei/reisehinweise-tuerkei.html' },
    { label: 'Turkmenistan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/turkmenistan/reisehinweise-turkmenistan.html' },
    { label: 'Tuvalu', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/tuvalu/reisehinweise-tuvalu.html' },
    { label: 'Uganda', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/uganda/reisehinweise-uganda.html' },
    { label: 'Ukraine', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/ukraine/reisehinweise-ukraine.html' },
    { label: 'Ungarn', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/ungarn/reisehinweise-ungarn.html' },
    { label: 'Uruguay', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/uruguay/reisehinweise-uruguay.html' },
    { label: 'USA', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/usa/reisehinweise-usa.html' },
    { label: 'Usbekistan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/usbekistan/reisehinweise-usbekistan.html' },
    { label: 'Vanuatu', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/vanuatu/reisehinweise-vanuatu.html' },
    { label: 'Vatikan', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/vatikan/reisehinweise-vatikan.html' },
    { label: 'Venezuela', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/venezuela/reisehinweise-venezuela.html' },
    { label: 'Vereinigte Arabische Emirate', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/vereinigte_arabischeemirate/reisehinweise-vereinigte-arabische-emirate.html' },
    { label: 'Vereinigtes Königreich', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/vereinigtes-koenigreich/reisehinweise-vereinigtes-koenigreich.html' },
    { label: 'Vietnam', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/vietnam/reisehinweise-vietnam.html' },
    { label: 'Zentralafrikanische Republik', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/zentralafrikanischerepublik/reisehinweise-zentralafrikanische-republik.html' },
    { label: 'Zypern', value: 'https://www.eda.admin.ch/content/eda/de/home/laender-reise-information/zypern/reisehinweise-zypern.html' },
];

export default countries;
